name: 'Mark new issues with needs-triage label'

on: [workflow_call]

jobs:
  label-new-issues:
    runs-on: ubuntu-latest
    steps:
      - name: initial labelling
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90  # v1.0.4, as of 2021-11-26
        with:
          add-labels: "needs-triage"
